// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:duckstore/firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );



class DefaultFirebaseOptions {
 
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVweN20x77ciWKXFASmRiJOMSLODJ4oFY',
    appId: '1:241547638352:web:b557f62eef31ee05520355',
    messagingSenderId: '241547638352',
    projectId: 'duckstore-81b90',
    authDomain: 'duckstore-81b90.firebaseapp.com',
    storageBucket: 'duckstore-81b90.appspot.com',
    measurementId: 'G-3FDEMZKMJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpIm8gmaaiQDfOxhaLIj70SxtOuc0ERw',
    appId: '1:241547638352:android:29c6c62a42c3fae6520355',
    messagingSenderId: '241547638352',
    projectId: 'duckstore-81b90',
    storageBucket: 'duckstore-81b90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAchSl9_fw_YlmyzDymaf4FwDrPGb5aj94',
    appId: '1:241547638352:ios:7d8c7e6ad3770595520355',
    messagingSenderId: '241547638352',
    projectId: 'duckstore-81b90',
    storageBucket: 'duckstore-81b90.appspot.com',
    iosBundleId: 'com.example.duckstore',
  );
}
